- hosts: manager
  become: true
  tasks:
  - name: Initialize Docker Swarm on the manager
    command: docker swarm init
    register: swarm_init
    changed_when: "'Error' not in swarm_init.stderr"

  - name: Get join token for worker nodes
    command: docker swarm join-token worker -q
    register: worker_token
    when: "'This node is already part of a swarm' not in swarm_init.stderr"
    changed_when: false

  - name: Set fact for worker join token
    set_fact:
      worker_join_token: "{{ worker_token.stdout }}"
    when: "'This node is already part of a swarm' not in swarm_init.stderr"

- hosts: workers
  become: true
  tasks:
  - name: Join the worker node to Docker Swarm
    command: docker swarm join --token {{ hostvars['manager']['worker_join_token'] }} {{ hostvars['manager']['ansible_host'] }}:2377

