name: Ansible Playbook Workflow

on:
  push:
    branches:
      - main
    paths:
      - ansible/inventory/inventory

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          cd ansible/inventory
          ansible-playbook -i inventory playbook.yaml
